resources:
  - name: git_repo_gradle
    type: GitRepo
    configuration:
      gitProvider: mkGithub
      path: Manokarthi2412/gradle-build
      branches:
        include: main
pipelines: 
  - name: gradle_ci
    steps:
      - name: build
        type: GradleBuild
        configuration:
          integrations:
            - name: mkartifactory
          inputResources:
            - name: git_repo_gradle
          gradleCommand: hello
          sourceLocation: . #optional
          
